-- ============================================================================
-- UCAio - Esquema relacional (Sprint 1)
-- Fiel al modelo ER: UCAio_modelo_ER.drawio.png
-- ============================================================================
-- Ejecutar con: npm run db:migrate
-- El script es idempotente: se puede correr varias veces sin romper nada.
-- ============================================================================

-- Extensiones -----------------------------------------------------------------
CREATE EXTENSION IF NOT EXISTS pgcrypto;   -- gen_random_uuid()

-- btree_gist habilita el EXCLUDE constraint que evita reservas solapadas.
-- Si el proveedor no la permite, el sistema sigue funcionando: la validacion
-- transaccional en la aplicacion (reserva.service.js) cubre el caso.
DO $$
BEGIN
  CREATE EXTENSION IF NOT EXISTS btree_gist;
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'No se pudo crear la extension btree_gist: %', SQLERRM;
END
$$;

-- Tipos ENUM ------------------------------------------------------------------
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'rol_usuario') THEN
    CREATE TYPE rol_usuario AS ENUM ('CONDUCTOR', 'PROPIETARIO');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'estado_cochera') THEN
    CREATE TYPE estado_cochera AS ENUM ('LIBRE', 'OCUPADA', 'RESERVADA', 'INACTIVA');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'estado_reserva') THEN
    CREATE TYPE estado_reserva AS ENUM ('PENDIENTE', 'CONFIRMADA', 'CANCELADA', 'FINALIZADA');
  END IF;
END
$$;

-- USUARIO ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS usuario (
  id_usuario    UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  nombre        VARCHAR(80)  NOT NULL,
  apellido      VARCHAR(80)  NOT NULL,
  email         VARCHAR(160) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  rol           rol_usuario  NOT NULL,
  telefono      VARCHAR(30),
  activo        BOOLEAN      NOT NULL DEFAULT TRUE,
  created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
  CONSTRAINT usuario_email_unico UNIQUE (email)
);

-- TIPO_VEHICULO ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS tipo_vehiculo (
  id_tipo_vehiculo SMALLINT    PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  nombre           VARCHAR(40) NOT NULL,
  CONSTRAINT tipo_vehiculo_nombre_unico UNIQUE (nombre)
);

-- ESTACIONAMIENTO -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS estacionamiento (
  id_estacionamiento UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
  id_propietario     UUID          NOT NULL,
  nombre             VARCHAR(120)  NOT NULL,
  direccion          VARCHAR(200)  NOT NULL,
  barrio_zona        VARCHAR(120),
  latitud            DECIMAL(9, 6),
  longitud           DECIMAL(9, 6),
  telefono_contacto  VARCHAR(30),
  email_contacto     VARCHAR(160),
  tarifa_hora        DECIMAL(10, 2) NOT NULL DEFAULT 0,
  publicado          BOOLEAN        NOT NULL DEFAULT FALSE,
  activo             BOOLEAN        NOT NULL DEFAULT TRUE,
  CONSTRAINT estacionamiento_propietario_fk
    FOREIGN KEY (id_propietario) REFERENCES usuario (id_usuario) ON DELETE RESTRICT,
  CONSTRAINT estacionamiento_tarifa_no_negativa CHECK (tarifa_hora >= 0),
  CONSTRAINT estacionamiento_latitud_valida  CHECK (latitud  IS NULL OR latitud  BETWEEN -90  AND 90),
  CONSTRAINT estacionamiento_longitud_valida CHECK (longitud IS NULL OR longitud BETWEEN -180 AND 180)
);

CREATE INDEX IF NOT EXISTS idx_estacionamiento_propietario ON estacionamiento (id_propietario);
CREATE INDEX IF NOT EXISTS idx_estacionamiento_publicado   ON estacionamiento (publicado, activo);

-- HORARIO ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS horario (
  id_horario         UUID     PRIMARY KEY DEFAULT gen_random_uuid(),
  id_estacionamiento UUID     NOT NULL,
  dia_semana         SMALLINT NOT NULL,
  hora_apertura      TIME     NOT NULL,
  hora_cierre        TIME     NOT NULL,
  CONSTRAINT horario_estacionamiento_fk
    FOREIGN KEY (id_estacionamiento) REFERENCES estacionamiento (id_estacionamiento) ON DELETE CASCADE,
  CONSTRAINT horario_dia_semana_valido CHECK (dia_semana BETWEEN 0 AND 6),
  CONSTRAINT horario_unico_por_dia UNIQUE (id_estacionamiento, dia_semana)
);

-- EXCEPCION -------------------------------------------------------------------
-- Modelada tal cual aparece en el diagrama (ver "Observaciones sobre el ER"
-- en el README: los tipos de `dia` y `horario` estan pendientes de revision).
CREATE TABLE IF NOT EXISTS excepcion (
  id                 UUID    PRIMARY KEY DEFAULT gen_random_uuid(),
  id_estacionamiento UUID    NOT NULL,
  dia                TIME,
  abierto            BOOLEAN NOT NULL DEFAULT FALSE,
  horario            TIMESTAMPTZ,
  hora_apertura      TIME,
  CONSTRAINT excepcion_estacionamiento_fk
    FOREIGN KEY (id_estacionamiento) REFERENCES estacionamiento (id_estacionamiento) ON DELETE CASCADE
);

-- VEHICULO --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS vehiculo (
  id_vehiculo      UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  id_conductor     UUID        NOT NULL,
  id_tipo_vehiculo SMALLINT    NOT NULL,
  patente          VARCHAR(12) NOT NULL,
  marca            VARCHAR(60),
  modelo           VARCHAR(60),
  activo           BOOLEAN     NOT NULL DEFAULT TRUE,
  CONSTRAINT vehiculo_conductor_fk
    FOREIGN KEY (id_conductor) REFERENCES usuario (id_usuario) ON DELETE CASCADE,
  CONSTRAINT vehiculo_tipo_fk
    FOREIGN KEY (id_tipo_vehiculo) REFERENCES tipo_vehiculo (id_tipo_vehiculo) ON DELETE RESTRICT,
  CONSTRAINT vehiculo_patente_unica UNIQUE (patente)
);

CREATE INDEX IF NOT EXISTS idx_vehiculo_conductor ON vehiculo (id_conductor);

-- COCHERA ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS cochera (
  id_cochera         UUID           PRIMARY KEY DEFAULT gen_random_uuid(),
  id_estacionamiento UUID           NOT NULL,
  id_tipo_vehiculo   SMALLINT       NOT NULL,
  identificador      VARCHAR(20)    NOT NULL,
  estado_actual      estado_cochera NOT NULL DEFAULT 'LIBRE',
  activo             BOOLEAN        NOT NULL DEFAULT TRUE,
  CONSTRAINT cochera_estacionamiento_fk
    FOREIGN KEY (id_estacionamiento) REFERENCES estacionamiento (id_estacionamiento) ON DELETE CASCADE,
  CONSTRAINT cochera_tipo_fk
    FOREIGN KEY (id_tipo_vehiculo) REFERENCES tipo_vehiculo (id_tipo_vehiculo) ON DELETE RESTRICT,
  CONSTRAINT cochera_identificador_unico UNIQUE (id_estacionamiento, identificador)
);

CREATE INDEX IF NOT EXISTS idx_cochera_estacionamiento ON cochera (id_estacionamiento);

-- RESERVA ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS reserva (
  id_reserva   UUID           PRIMARY KEY DEFAULT gen_random_uuid(),
  id_conductor UUID           NOT NULL,
  id_vehiculo  UUID           NOT NULL,
  id_cochera   UUID           NOT NULL,
  inicio       TIMESTAMPTZ    NOT NULL,
  fin          TIMESTAMPTZ    NOT NULL,
  estado       estado_reserva NOT NULL DEFAULT 'PENDIENTE',
  created_at   TIMESTAMPTZ    NOT NULL DEFAULT now(),
  CONSTRAINT reserva_conductor_fk
    FOREIGN KEY (id_conductor) REFERENCES usuario (id_usuario) ON DELETE RESTRICT,
  CONSTRAINT reserva_vehiculo_fk
    FOREIGN KEY (id_vehiculo) REFERENCES vehiculo (id_vehiculo) ON DELETE RESTRICT,
  CONSTRAINT reserva_cochera_fk
    FOREIGN KEY (id_cochera) REFERENCES cochera (id_cochera) ON DELETE RESTRICT,
  CONSTRAINT reserva_rango_valido CHECK (fin > inicio)
);

CREATE INDEX IF NOT EXISTS idx_reserva_cochera_rango ON reserva (id_cochera, inicio, fin);
CREATE INDEX IF NOT EXISTS idx_reserva_conductor     ON reserva (id_conductor);

-- Garantia a nivel base de datos: una cochera no puede tener dos reservas
-- vigentes (PENDIENTE o CONFIRMADA) que se solapen en el tiempo.
-- Es la red de seguridad del chequeo transaccional de reserva.service.js.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'reserva_sin_solapamiento'
  ) THEN
    ALTER TABLE reserva ADD CONSTRAINT reserva_sin_solapamiento
      EXCLUDE USING gist (
        id_cochera WITH =,
        tstzrange(inicio, fin, '[)') WITH &&
      ) WHERE (estado IN ('PENDIENTE', 'CONFIRMADA'));
  END IF;
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'No se pudo crear el EXCLUDE constraint reserva_sin_solapamiento: %', SQLERRM;
END
$$;
